// expo-app/src/chat/ChatPanel.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { View } from 'react-native';
import { gamesApi } from '@/api/endpoints';
import type { ChatMessage } from '@/api/types';
import { useSignedInUser } from '@/auth/AuthProvider';
import { AppText } from '@/components/AppText';
import { Button } from '@/components/Button';
import { Card } from '@/components/Card';
import { FormError } from '@/components/FormError';
import { TextField } from '@/components/TextField';
import { applyServerErrors } from '@/forms/applyServerErrors';
import { useI18n } from '@/i18n/I18nProvider';
import { useGameEvent, useRealtimeConnected } from '@/realtime/RealtimeProvider';
import { useTheme } from '@/theme/useTheme';

/** How often to check for messages while live updates are down. */
const FALLBACK_POLL_MS = 5000;
const MAX_LENGTH = 500;

const chatKey = (code: string) => ['chat', code] as const;

/** Adds messages the list doesn't have yet, keeping them in order. */
function merge(current: ChatMessage[] | undefined, incoming: ChatMessage[]): ChatMessage[] {
  const known = new Set((current ?? []).map((message) => message.id));
  return [...(current ?? []), ...incoming.filter((message) => !known.has(message.id))].sort((a, b) => a.id - b.id);
}

/** Text chat for the game's players, in the lobby. */
export function ChatPanel({ code, gameId }: { code: string; gameId: number }) {
  const { t } = useI18n();
  const { colors, spacing, radius } = useTheme();
  const me = useSignedInUser();
  const queryClient = useQueryClient();
  const connected = useRealtimeConnected();
  const [draft, setDraft] = useState('');
  const [error, setError] = useState<string | null>(null);

  const messages = useQuery({
    queryKey: chatKey(code),
    queryFn: () => gamesApi.messages(code),
    refetchInterval: connected ? false : FALLBACK_POLL_MS,
  });

  useGameEvent<{ message: ChatMessage }>(gameId, '.chat.message', ({ message }) =>
    queryClient.setQueryData<ChatMessage[]>(chatKey(code), (current) => merge(current, [message])),
  );

  const send = useMutation({
    mutationFn: (body: string) => gamesApi.postMessage(code, body),
    onSuccess: (message) => {
      setDraft('');
      queryClient.setQueryData<ChatMessage[]>(chatKey(code), (current) => merge(current, [message]));
    },
    onError: (caught) => setError(applyServerErrors(caught, () => {}, []) ?? t('Something went wrong.')),
  });

  const submit = () => {
    const body = draft.trim();
    if (!body || send.isPending) return;
    setError(null);
    send.mutate(body);
  };

  const list = messages.data ?? [];

  return (
    <Card testID="chat-panel">
      <AppText variant="heading">{t('Chat')}</AppText>
      <View testID="chat-messages" style={{ gap: spacing.sm }}>
        {list.length === 0 ? <AppText variant="muted">{t('No messages yet. Say hello!')}</AppText> : null}
        {list.map((message) => {
          const mine = message.user.id === me.id;
          return (
            <View
              key={message.id}
              testID={`chat-message-${message.id}`}
              style={{
                alignSelf: mine ? 'flex-end' : 'flex-start',
                maxWidth: '85%',
                backgroundColor: mine ? colors.secondary : colors.muted,
                borderRadius: radius.lg,
                paddingHorizontal: spacing.md,
                paddingVertical: spacing.sm,
              }}
            >
              <AppText style={{ fontWeight: '600' }}>{message.user.codename}</AppText>
              <AppText>{message.body}</AppText>
            </View>
          );
        })}
      </View>
      <TextField
        testID="input-chat"
        label={t('Write a message')}
        value={draft}
        onChangeText={setDraft}
        maxLength={MAX_LENGTH}
        returnKeyType="send"
        onSubmitEditing={submit}
        submitBehavior="submit"
      />
      <FormError message={error} />
      <Button
        testID="btn-chat-send"
        label={t('Send')}
        loading={send.isPending}
        disabled={!draft.trim()}
        onPress={submit}
      />
    </Card>
  );
}

// laravel-app/resources/js/components/game/ChatPanel.vue
<script setup lang="ts">
import { usePage } from '@inertiajs/vue3';
import { MessageSquare, Send } from '@lucide/vue';
import { nextTick, onBeforeUnmount, onMounted, ref } from 'vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useTrans } from '@/composables/useTrans';
import echo from '@/echo';
import { jsonFetch } from '@/lib/jsonFetch';
import type { Game } from '@/types/game';

interface ChatMessage {
    id: number;
    body: string;
    created_at: string | null;
    user: { id: number; codename: string; name: string };
}

/** How often to check for messages while live updates are down. */
const FALLBACK_POLL_MS = 5000;
const MAX_LENGTH = 500;

/** Text chat for the game's players, in the lobby. */
const props = defineProps<{ game: Game }>();

const { t } = useTrans();
const page = usePage<{ auth: { user: { id: number } } }>();
const messages = ref<ChatMessage[]>([]);
const draft = ref('');
const sending = ref(false);
const error = ref<string | null>(null);
const list = ref<HTMLElement | null>(null);
const connection = echo.connector.pusher.connection;
const channelName = `game.${props.game.id}`;
let subscribed = false;
let timer: number | undefined;

async function scrollToEnd() {
    await nextTick();
    list.value?.scrollTo({ top: list.value.scrollHeight });
}

/** Adds messages it doesn't have yet, keeping them in order. */
function merge(incoming: ChatMessage[]) {
    const known = new Set(messages.value.map((message) => message.id));
    const fresh = incoming.filter((message) => !known.has(message.id));

    if (fresh.length > 0) {
        messages.value = [...messages.value, ...fresh].sort(
            (a, b) => a.id - b.id,
        );
        void scrollToEnd();
    }
}

async function load() {
    merge(
        await jsonFetch<ChatMessage[]>(
            `/games/${props.game.code}/messages`,
        ).catch(() => []),
    );
}

async function send() {
    const body = draft.value.trim();

    if (!body || sending.value) {
        return;
    }

    sending.value = true;
    error.value = null;

    try {
        merge([
            await jsonFetch<ChatMessage>(`/games/${props.game.code}/messages`, {
                method: 'POST',
                body: { body },
            }),
        ]);
        draft.value = '';
    } catch (caught) {
        error.value = caught instanceof Error ? caught.message : String(caught);
    } finally {
        sending.value = false;
    }
}

function time(iso: string | null): string {
    return iso
        ? new Date(iso).toLocaleTimeString([], {
              hour: '2-digit',
              minute: '2-digit',
          })
        : '';
}

onMounted(() => {
    void load();

    // The lobby's game channel; useGameChannel owns joining and leaving it.
    echo.private(channelName)
        .subscribed(() => (subscribed = true))
        .error(() => (subscribed = false))
        .listen('.chat.message', (payload: { message: ChatMessage }) =>
            merge([payload.message]),
        );
    // Already subscribed (by the lobby) means no new "subscribed" event.
    subscribed ||= Boolean(
        echo.connector.pusher.channel(`private-${channelName}`)?.subscribed,
    );

    timer = window.setInterval(() => {
        const live = connection.state === 'connected' && subscribed;

        if (!live && document.visibilityState === 'visible') {
            void load();
        }
    }, FALLBACK_POLL_MS);
});

onBeforeUnmount(() => {
    window.clearInterval(timer);
    echo.private(channelName).stopListening('.chat.message');
});
</script>

<template>
    <div
        id="chat-panel"
        class="rounded-xl border border-sidebar-border/70 p-4 dark:border-sidebar-border"
    >
        <h2 class="flex items-center gap-2 font-semibold">
            <MessageSquare class="size-5" />
            {{ t('Chat') }}
        </h2>

        <ul
            ref="list"
            id="chat-messages"
            class="mt-3 max-h-72 space-y-2 overflow-y-auto text-sm"
        >
            <li v-if="messages.length === 0" class="text-muted-foreground">
                {{ t('No messages yet. Say hello!') }}
            </li>
            <li
                v-for="message in messages"
                :key="message.id"
                :class="
                    message.user.id === page.props.auth.user.id
                        ? 'ml-8 rounded-lg bg-primary/5 px-3 py-2'
                        : 'mr-8 rounded-lg bg-muted px-3 py-2'
                "
            >
                <span class="flex items-baseline justify-between gap-2">
                    <span class="font-semibold">{{
                        message.user.codename
                    }}</span>
                    <span class="text-xs text-muted-foreground">{{
                        time(message.created_at)
                    }}</span>
                </span>
                <span class="block break-words whitespace-pre-wrap">{{
                    message.body
                }}</span>
            </li>
        </ul>

        <form id="chat-form" class="mt-3 flex gap-2" @submit.prevent="send">
            <Input
                id="input-chat"
                v-model="draft"
                :maxlength="MAX_LENGTH"
                :placeholder="t('Write a message')"
                autocomplete="off"
            />
            <Button
                id="btn-chat-send"
                type="submit"
                :disabled="sending || !draft.trim()"
                :aria-label="t('Send')"
            >
                <Send />
            </Button>
        </form>
        <p v-if="error" class="mt-2 text-sm text-red-600">{{ error }}</p>
    </div>
</template>
