// expo-app/src/game/Roster.tsx
import type { ReactNode } from 'react';
import { Pressable, View } from 'react-native';
import type { Game, Player } from '@/api/types';
import { AppText } from '@/components/AppText';
import { Badge } from '@/components/Badge';
import { Button } from '@/components/Button';
import { Card } from '@/components/Card';
import { OnlineDot } from '@/components/OnlineDot';
import { useOnlineUserIds } from '@/realtime/RealtimeProvider';
import { useTheme } from '@/theme/useTheme';
import { openPlayerMenu } from './playerMenu';
import { useLobbyControls } from './useLobbyControls';

/**
 * Players by score with readiness. Between rounds the host taps a player
 * to make them host or remove them. `badge` adds game-specific markers.
 */
export function Roster({ game, inRound, badge }: { game: Game; inRound: boolean; badge?: (player: Player) => ReactNode }) {
  const { me, t, isHost, mine, busy, run } = useLobbyControls(game);
  const { spacing } = useTheme();
  const online = useOnlineUserIds();

  return (
    <Card>
      <AppText variant="heading">{t('Players')}</AppText>
      {[...(game.players ?? [])]
        .sort((a, b) => (b.score ?? 0) - (a.score ?? 0))
        .map((player) => (
          <Pressable
            key={player.id}
            testID={`roster-${player.user.id}`}
            disabled={!isHost || inRound || player.user.id === me.id}
            accessibilityHint={isHost ? t('Make host') : undefined}
            onPress={() => openPlayerMenu(t, player.user, (next) => run(next))}
            style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm }}
          >
            <OnlineDot online={online.has(player.user.id)} />
            <View style={{ flex: 1 }}>
              <AppText>
                {player.user.codename}
                {player.user.id === me.id ? ` (${t('you')})` : ''}
              </AppText>
              <AppText variant="muted">
                {player.user.name} · {player.status === 'ready' ? t('Ready') : t('Not ready')}
              </AppText>
            </View>
            {player.is_host ? <Badge label={t('Host')} /> : null}
            {badge?.(player)}
            <AppText variant="muted" testID={`score-${player.user.id}`}>
              {t(':score pts', { score: player.score ?? 0 })}
            </AppText>
          </Pressable>
        ))}
      {mine && !inRound ? (
        <Button
          testID="btn-toggle-ready"
          label={mine.status === 'ready' ? t('Mark me not ready') : t('Mark me ready')}
          variant="secondary"
          disabled={busy}
          onPress={() => run({ type: 'ready' })}
        />
      ) : null}
    </Card>
  );
}

// laravel-app/resources/js/components/game/Roster.vue
<script setup lang="ts">
import { computed } from 'vue';
import PlayerActions from '@/components/game/PlayerActions.vue';
import { Button } from '@/components/ui/button';
import { useLobby } from '@/composables/useLobby';
import type { Game, Player } from '@/types/game';

/**
 * Players by score, with readiness, the host's per-player actions between
 * rounds, and a `badge` slot for game-specific markers (voted, asking).
 */
const props = defineProps<{ game: Game; inRound: boolean }>();

defineSlots<{ badge?(props: { player: Player }): unknown }>();

const { t, myId, isHost, me, busy, act } = useLobby(() => props.game);
const scoreboard = computed(() =>
    [...props.game.players].sort((a, b) => b.score - a.score),
);
</script>

<template>
    <div
        id="operatives-roster"
        class="rounded-xl border border-sidebar-border/70 p-4 dark:border-sidebar-border"
    >
        <div class="mb-2 flex items-center justify-between gap-2">
            <h2 class="font-semibold">{{ t('Players') }}</h2>
            <Button
                v-if="me && !inRound"
                id="btn-toggle-ready"
                variant="outline"
                size="sm"
                :disabled="busy"
                @click="act('ready')"
            >
                {{
                    me.status === 'ready'
                        ? t('Mark me not ready')
                        : t('Mark me ready')
                }}
            </Button>
        </div>
        <ul id="roster-list" class="space-y-1">
            <li
                v-for="player in scoreboard"
                :key="player.id"
                class="flex items-center justify-between gap-2"
            >
                <span class="flex items-center gap-2">
                    <span
                        :class="[
                            'inline-block h-2 w-2 rounded-full',
                            player.status === 'ready'
                                ? 'bg-green-500'
                                : 'bg-muted-foreground/40',
                        ]"
                        :title="
                            player.status === 'ready'
                                ? t('Ready')
                                : t('Not ready')
                        "
                    />
                    {{ player.user.codename }}
                    <span class="text-sm text-muted-foreground">{{
                        player.user.name
                    }}</span>
                    <span
                        v-if="player.is_host"
                        class="text-xs text-muted-foreground"
                        >({{ t('Host') }})</span
                    >
                    <span
                        v-if="player.user.id === myId"
                        class="text-xs text-muted-foreground"
                        >({{ t('you') }})</span
                    >
                    <slot name="badge" :player="player" />
                </span>
                <span class="flex items-center gap-2">
                    <PlayerActions
                        v-if="isHost && !inRound && player.user.id !== myId"
                        :code="game.code"
                        :player="player.user"
                    />
                    <span class="text-xs text-muted-foreground">{{
                        t(':score pts', { score: player.score })
                    }}</span>
                </span>
            </li>
        </ul>
    </div>
</template>
