// laravel-app/resources/js/components/game/RoundHistory.vue
<script setup lang="ts">
import { History } from '@lucide/vue';
import { useLobby } from '@/composables/useLobby';
import { useTrans } from '@/composables/useTrans';
import type { Game } from '@/types/game';

const props = defineProps<{ game: Game }>();

const { t, pick } = useTrans();
const { playerName } = useLobby(() => props.game);

function spyOutcome(entry: NonNullable<Game['history']>[number]): string {
    if (entry.ending === 'abandoned') {
        return t('Abandoned');
    }

    return entry.winning_team === 'spies' ? t('Spies won') : t('Loyalists won');
}

function phraseOutcome(entry: NonNullable<Game['history']>[number]): string {
    if (entry.ending === 'guessed') {
        return t(':player guessed it', {
            player: playerName(entry.winner_user_id ?? null),
        });
    }

    return entry.ending === 'abandoned'
        ? t('Abandoned')
        : t('Nobody guessed it');
}
</script>

<template>
    <details
        v-if="game.history?.length"
        id="round-history"
        class="rounded-xl border border-sidebar-border/70 p-4 dark:border-sidebar-border"
    >
        <summary class="flex cursor-pointer items-center gap-2 font-semibold">
            <History class="size-4" />
            {{ t('Previous rounds') }} ({{ game.history.length }})
        </summary>
        <ol class="mt-2 space-y-1 text-sm">
            <li v-for="entry in game.history" :key="entry.number">
                <span class="font-medium">{{
                    t('Round :number', { number: entry.number })
                }}</span>
                ·
                <template v-if="game.game_type === 'phrase'">
                    “{{ entry.phrase }}” · {{ phraseOutcome(entry) }}
                </template>
                <template v-else>
                    {{ pick(entry.location) }} · {{ spyOutcome(entry) }} ·
                    {{ t('Spies') }}:
                    {{
                        (entry.spy_user_ids ?? [])
                            .map((id) => playerName(id))
                            .join(', ')
                    }}
                </template>
            </li>
        </ol>
    </details>
</template>

// expo-app/src/game/RoundHistory.tsx
import { useState } from 'react';
import { Pressable } from 'react-native';
import type { Game, HistoryEntry } from '@/api/types';
import { AppText } from '@/components/AppText';
import { Card } from '@/components/Card';
import { useI18n } from '@/i18n/I18nProvider';
import { operativeName } from './labels';

/** Earlier rounds of this game, collapsed until tapped. */
export function RoundHistory({ game }: { game: Game }) {
  const { t, place } = useI18n();
  const [open, setOpen] = useState(false);
  const history = game.history ?? [];
  if (history.length === 0) return null;

  const name = (id: number | null | undefined) => operativeName(game.players, id ?? null, t('a departed player'));

  const outcome = (entry: HistoryEntry) => {
    if (entry.ending === 'abandoned') return t('Abandoned');
    if (game.game_type === 'phrase') {
      return entry.ending === 'guessed' ? t(':player guessed it', { player: name(entry.winner_user_id) }) : t('Nobody guessed it');
    }
    return entry.winning_team === 'spies' ? t('Spies won') : t('Loyalists won');
  };

  return (
    <Card testID="round-history">
      <Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} onPress={() => setOpen((value) => !value)}>
        <AppText variant="heading">
          {open ? '▾' : '▸'} {t('Previous rounds')} ({history.length})
        </AppText>
      </Pressable>
      {open
        ? history.map((entry) => (
            <AppText key={entry.number} testID={`history-${entry.number}`}>
              {t('Round :number', { number: entry.number })} ·{' '}
              {game.game_type === 'phrase' ? `“${entry.phrase}”` : place(entry.location)} · {outcome(entry)}
              {game.game_type === 'spy' && entry.spy_user_ids?.length
                ? ` · ${t('Spies')}: ${entry.spy_user_ids.map((id) => name(id)).join(', ')}`
                : ''}
            </AppText>
          ))
        : null}
    </Card>
  );
}
